-|23-08-2022 16:27|-Ошибка  {'model': 'products.propertycategory', 'pk': 39, 'fields': {'category': 5, 'property': 11, 'filtered': False, 'filter_position': 1}}: Problem installing fixtures: insert or update on table "products_propertycategory" violates foreign key constraint "products_propertycat_category_id_e9c27709_fk_products_"
DETAIL:  Key (category_id)=(5) is not present in table "products_category".

-|23-08-2022 16:27|-Ошибка  {'model': 'products.propertycategory', 'pk': 40, 'fields': {'category': 5, 'property': 12, 'filtered': False, 'filter_position': 1}}: Problem installing fixtures: insert or update on table "products_propertycategory" violates foreign key constraint "products_propertycat_category_id_e9c27709_fk_products_"
DETAIL:  Key (category_id)=(5) is not present in table "products_category".

-|23-08-2022 16:27|-Ошибка  {'model': 'products.propertycategory', 'pk': 41, 'fields': {'category': 5, 'property': 13, 'filtered': False, 'filter_position': 1}}: Problem installing fixtures: insert or update on table "products_propertycategory" violates foreign key constraint "products_propertycat_category_id_e9c27709_fk_products_"
DETAIL:  Key (category_id)=(5) is not present in table "products_category".

-|23-08-2022 16:27|-Ошибка  {'model': 'products.propertycategory', 'pk': 42, 'fields': {'category': 5, 'property': 15, 'filtered': False, 'filter_position': 1}}: Problem installing fixtures: insert or update on table "products_propertycategory" violates foreign key constraint "products_propertycat_category_id_e9c27709_fk_products_"
DETAIL:  Key (category_id)=(5) is not present in table "products_category".

-|23-08-2022 16:28|-Ошибка  {'model': 'promotions.promotionsshowproduct', 'pk': 1, 'fields': {'limit_day_show_product': 3, 'product_show': 2}}: Problem installing fixture '/home/pavlove/Рабочий стол/python_django_team9/media/admin_fixtures/data.json': PeriodicTask matching query does not exist.
-|23-08-2022 16:28|-Ошибка  {'model': 'products.product', 'fields': {'name': 'Tasks2', 'article': 'tasks2', 'description': '', 'price': '1500.00', 'rating': '0.00', 'flag_limit': False, 'category': 12, 'tag': '', 'promotion_group': 1, 'tags': []}}: Problem installing fixtures: insert or update on table "products_product" violates foreign key constraint "products_product_category_id_9b594869_fk_products_category_id"
DETAIL:  Key (category_id)=(12) is not present in table "products_category".

-|23-08-2022 16:28|-Ошибка  {'model': 'products.product', 'fields': {'name': 'Tasks3', 'description': '', 'price': '1500.00', 'rating': '0.00', 'flag_limit': False, 'category': 34, 'tag': '', 'promotion_group': 1, 'tags': []}}: Problem installing fixtures: insert or update on table "products_product" violates foreign key constraint "products_product_category_id_9b594869_fk_products_category_id"
DETAIL:  Key (category_id)=(34) is not present in table "products_category".

-|23-08-2022 16:28|-Ошибка  {'model': 'products.product', 'fields': {'name': 'Tasks4', 'article': 'tasks4', 'description': '', 'price': '610.00', 'rating': '0.00', 'flag_limit': False, 'category': 17, 'tag': '', 'promotion_group': None, 'tags': []}}: Problem installing fixtures: insert or update on table "products_product" violates foreign key constraint "products_product_category_id_9b594869_fk_products_category_id"
DETAIL:  Key (category_id)=(17) is not present in table "products_category".

-|23-08-2022 16:28|-Ошибка  {'model': 'django_celery_beat.periodictask', 'pk': 2, 'fields': {'name': 'celery.backend_cleanup', 'task': 'celery.backend_cleanup', 'interval': None, 'crontab': 1, 'solar': None, 'clocked': None, 'args': '[]', 'kwargs': '{}', 'queue': None, 'exchange': None, 'routing_key': None, 'headers': '{}', 'priority': None, 'expires': None, 'expire_seconds': 43200, 'one_off': False, 'start_time': None, 'enabled': True, 'last_run_at': None, 'total_run_count': 0, 'date_changed': '2022-07-06T20:30:00.682Z', 'description': ''}}: Problem installing fixtures: insert or update on table "django_celery_beat_periodictask" violates foreign key constraint "django_celery_beat_p_crontab_id_d3cba168_fk_django_ce"
DETAIL:  Key (crontab_id)=(1) is not present in table "django_celery_beat_crontabschedule".

